# Generated by Django 5.0.6 on 2024-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoneR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('code', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, choices=[('create', 'create'), ('forgot', 'forgot')], max_length=100, null=True)),
                ('verification_token', models.CharField(max_length=200, null=True)),
                ('used', models.BooleanField(default=False, null=True)),
                ('timeout', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
