# Generated by Django 5.0.6 on 2024-07-16 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoneR', '0004_alter_user_profile_picture_userbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 16, 6, 49, 20, 836281, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
