# Generated by Django 5.0.6 on 2024-07-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UoneR', '0006_user_delete_alter_userbusiness_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
